all_tasks_pool = [
    {"id": 1, "task_name": "Water the community garden plot", "status": "Pending", "volunteer": "None", "points": 20, "priority": "High", "group": "All"},
    {"id": 2, "task_name": "Refill the local park bird feeders", "status": "Pending", "volunteer": "None", "points": 10, "priority": "Low", "group": "All"},
    {"id": 3, "task_name": "Plant new wildflower seeds by the fence", "status": "Pending", "volunteer": "None", "points": 30, "priority": "Medium", "group": "All"},
    {"id": 4, "task_name": "Pick up litter along the main park trail", "status": "Pending", "volunteer": "None", "points": 25, "priority": "High", "group": "All"},
    {"id": 5, "task_name": "Sort donated books for the community free library", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "All"},
    {"id": 6, "task_name": "Clean and scrub the community compost bins", "status": "Pending", "volunteer": "None", "points": 35, "priority": "Medium", "group": "All"},
    {"id": 7, "task_name": "Plant a new sapling tree at the recreation center", "status": "Pending", "volunteer": "None", "points": 50, "priority": "High", "group": "All"},
    {"id": 8, "task_name": "Wipe down and clean public park benches", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "All"},
    {"id": 9, "task_name": "Help build a new raised garden bed", "status": "Pending", "volunteer": "None", "points": 45, "priority": "High", "group": "All"},
    {"id": 10, "task_name": "Distribute water conservation flyers to neighbors", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "All"},
    {"id": 11, "task_name": "Collect reusable grocery bags for the food pantry", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "All"},
    {"id": 12, "task_name": "Remove plastic tags and ties from park fences", "status": "Pending", "volunteer": "None", "points": 10, "priority": "Low", "group": "All"},
    {"id": 13, "task_name": "Rake and bag fallen leaves in the shared courtyard", "status": "Pending", "volunteer": "None", "points": 25, "priority": "Medium", "group": "All"},
    {"id": 14, "task_name": "Set up signs for the upcoming eco-fair", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "All"},
    {"id": 15, "task_name": "Clear fallen branches blocks from the sidewalk", "status": "Pending", "volunteer": "None", "points": 30, "priority": "High", "group": "All"},
    {"id": 16, "task_name": "Organize tool shed items in the community garden", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Low", "group": "All"},
    {"id": 17, "task_name": "Shred cardboard boxes for garden mulch pile", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Medium", "group": "All"},
    {"id": 18, "task_name": "Clean up stray plastic wraps near the local shops", "status": "Pending", "volunteer": "None", "points": 25, "priority": "High", "group": "All"},
    {"id": 19, "task_name": "Empty the school recycling bins", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 20, "task_name": "Host an environmental sorting workshop", "status": "Pending", "volunteer": "None", "points": 40, "priority": "High", "group": "EcoSeniors"},
    {"id": 21, "task_name": "Label native plants with educational tags", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Low", "group": "EcoSeniors"},
    {"id": 22, "task_name": "Monitor and record weekly community garden growth", "status": "Pending", "volunteer": "None", "points": 25, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 23, "task_name": "Collect used batteries for safe specialized recycling", "status": "Pending", "volunteer": "None", "points": 30, "priority": "High", "group": "EcoSeniors"},
    {"id": 24, "task_name": "Inspect garden irrigation system for water leaks", "status": "Pending", "volunteer": "None", "points": 35, "priority": "High", "group": "EcoSeniors"},
    {"id": 25, "task_name": "Prune overgrown tomato vines in greenhouse", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 26, "task_name": "Sort and bundle newspaper drop-offs", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "EcoSeniors"},
    {"id": 27, "task_name": "Check bee hotel boxes for winter damage", "status": "Pending", "volunteer": "None", "points": 25, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 28, "task_name": "Create a display poster for energy-saving tips", "status": "Pending", "volunteer": "None", "points": 30, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 29, "task_name": "Gather organic scraps from the cooking class", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "EcoSeniors"},
    {"id": 30, "task_name": "Repair broken wooden borders around flowerbeds", "status": "Pending", "volunteer": "None", "points": 45, "priority": "High", "group": "EcoSeniors"},
    {"id": 31, "task_name": "Audit classroom lights to ensure they are turned off", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "EcoSeniors"},
    {"id": 32, "task_name": "Clean empty seed starter trays for reuse next spring", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "EcoSeniors"},
    {"id": 33, "task_name": "Wash the shared harvest baskets", "status": "Pending", "volunteer": "None", "points": 10, "priority": "Low", "group": "EcoSeniors"},
    {"id": 34, "task_name": "Clear weeds from the community pathway", "status": "Pending", "volunteer": "None", "points": 40, "priority": "High", "group": "GreenStreet Team"},
    {"id": 35, "task_name": "Clear storm drains of plastic bottles and leaves", "status": "Pending", "volunteer": "None", "points": 45, "priority": "High", "group": "GreenStreet Team"},
    {"id": 36, "task_name": "Paint protective eco-coating on wooden park fences", "status": "Pending", "volunteer": "None", "points": 50, "priority": "High", "group": "GreenStreet Team"},
    {"id": 37, "task_name": "Pick up highway exit ramp litter safely", "status": "Pending", "volunteer": "None", "points": 40, "priority": "High", "group": "GreenStreet Team"},
    {"id": 38, "task_name": "Scrape illegal plastic stickers off public lampposts", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 40, "task_name": "Pick up microplastics on the river bank", "status": "Pending", "volunteer": "None", "points": 30, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 41, "task_name": "Sweep gravel and dirt back into the walking trails", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "GreenStreet Team"},
    {"id": 42, "task_name": "Tie up loose recycling bundles on pickup morning", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 43, "task_name": "Install reflective tape on neighborhood recycling bins", "status": "Pending", "volunteer": "None", "points": 15, "priority": "Low", "group": "GreenStreet Team"},
    {"id": 44, "task_name": "Cut down invasive ivy vines suffocating oak trees", "status": "Pending", "volunteer": "None", "points": 45, "priority": "High", "group": "GreenStreet Team"},
    {"id": 45, "task_name": "Dig holes for the upcoming hedge planting weekend", "status": "Pending", "volunteer": "None", "points": 35, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 46, "task_name": "Sort electronic waste drop-offs at the depot", "status": "Pending", "volunteer": "None", "points": 30, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 47, "task_name": "Pick up stray fishing lines by the lake dock", "status": "Pending", "volunteer": "None", "points": 25, "priority": "High", "group": "GreenStreet Team"},
    {"id": 48, "task_name": "Replace old light bulbs with energy-efficient LEDs", "status": "Pending", "volunteer": "None", "points": 20, "priority": "Medium", "group": "GreenStreet Team"},
    {"id": 49, "task_name": "Wipe down the neighborhood solar panel array", "status": "Pending", "volunteer": "None", "points": 40, "primary": "High", "group": "GreenStreet Team"},
    {"id": 50, "task_name": "Check water clarity level at the local stream", "status": "Pending", "volunteer": "None", "points": 25, "priority": "Low", "group": "GreenStreet Team"}
]